rpc_backend:
  name: "rpc-backend"
  replicaCount: 1
  labels: 
    app: "rpc-backend"
  template:
    labels: 
      app: "rpc-backend"
  container:
    name: rpc-backend-app
    image: ghcr.io/govstackworkinggroup/sandbox-app-rpc-backend:latest
    imagePullPolicy: "Always"
  profiles: "container"
  dbPersist: 
    volumeMountName: "rpc-backend-pvc"
    path: "./dbdata/rpcdata"
    mountPath: "/workspace/dbdata"
    storage: 1Gi
    flushStorageOnInit: false
  service:
    name: "rpc-backend"
    type: ClusterIP
    port: 8080
    targetPort: 8080

frontend:
  name: "high-school-frontend"
  replicaCount: 1
  labels:
    app: "high-school-frontend"
  template:
    labels:
      app: "high-school-frontend"
  container:
    name: high-school-frontend
    image: ghcr.io/govstackworkinggroup/sandbox-usecase-bp-frontend:latest
    imagePullPolicy: "Always"
  profiles: "container"
  service:
    name: "frontend"
    type: ClusterIP
    port: 80
    targetPort: 80
tls:
  dnsNames: "bp.playground.sandbox-playground.com"
  certificateName: "high-school-tls"
