backend:
  name: "cross-border-backend"
  containers:
    image: ghcr.io/govstackworkinggroup/sandbox-usecase-cross-border-payment-backend:latest
  signature: "placeholdertext"
  service:
    type: ClusterIP
    port: 8080
    targetPort: 8080
tls:
  dnsNames: "cross-border-pay.sandbox.govstack.global"
  certificateName: "cross-border-tls"
ui:
  name: "cross-border-frontend"
  replicaCount: 1
  labels:
    app: "cross-border-frontend"
  template:
    labels:
      app: "cross-border-frontend"
  container:
    name: cross-border-frontend
    image: ghcr.io/govstackworkinggroup/sandbox-usecase-cross-border-payment:latest
    imagePullPolicy: Always
  profiles: "cross-border-frontend"
frontsvc:
  name: "cross-border-frontend"
  type: ClusterIP
  port: 80
  targetPort: 80