name: "sandbox"
replicaCount: 1
labels: 
  app: "sandbox"
template:
  labels: 
    app: "sandbox"
containers:
  name: sandbox
  image: ghcr.io/govstackworkinggroup/sandbox-landingpage:0.0.1
  imagePullPolicy: "Always"
profiles: "container"
service:
  name: "sandbox"
  type: ClusterIP
  port: 80
  targetPort: 80
tls:
  dnsNames: "sandbox.govstack.global"
  certificateName: "sandbox-tls"